name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite (UTC)
  workflow_dispatch:       # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: Lucas-1234567890
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit generated snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate snake"
          add: "output/github-contribution-grid-snake.svg"
